/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.sun.glass.events.KeyEvent;
import java.awt.Font;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Swapnil
 */
public class Billing extends javax.swing.JFrame {

    /**
     * Creates new form Billing
     */
    Set<String> s;
    DefaultTableModel model;
    int no_items=0, total=0, cgst=0, sgst=0;
    
    public Billing() throws IOException { 
        initComponents();
        setInvoiceNo();
        setDate();
        tfGSTIN.setText("73DQNRH7981Z7GX");
        tfGSTIN.setEditable(false);
        tfPID.setEditable(false);
        tfUnit.setEditable(false);
        tfPrice.setEditable(false);
        tfDiscount.setEditable(false);
        tfAmount.setEditable(false);
        tfNo.setEditable(false);
        tfCGST.setEditable(false);
        tfSGST.setEditable(false);
        tfTotal.setEditable(false);
        autoSearch();
        model = (DefaultTableModel) tblProd.getModel();
        tblProd.getTableHeader().setFont(new Font("Tahoma",Font.PLAIN,18));
        tblProd.getColumnModel().getColumn(0).setPreferredWidth(110);
        tblProd.getColumnModel().getColumn(1).setPreferredWidth(190);
        tblProd.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblProd.getColumnModel().getColumn(3).setPreferredWidth(155);
        tblProd.setRowHeight(25);
    }
    
    public Billing(String str)
    {
        
    }
    
    public void setInvoiceNo() throws IOException
    {
        File file = new File("invoiceNo.txt");
        BufferedReader br = new BufferedReader(new FileReader(file)); 
        String st = br.readLine();
        tfInvoiceNo.setText(st);
        tfInvoiceNo.setEditable(false);
        br.close();
        int no = Integer.parseInt(st);
        no = no+1;
        BufferedWriter bw = new BufferedWriter(new FileWriter(file));
        bw.write(Integer.toString(no));    
        bw.close();
    }
    
    public void setDate()
    {
        LocalDateTime myDateObj = LocalDateTime.now();
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
        String formattedDate = myDateObj.format(myFormatObj);
        tfDate.setText(formattedDate);
        tfDate.setEditable(false);
    }
    
    public void autoSearch()
    {
        s = new TreeSet<String>();
        s.add("ALMOND"); s.add("ALUMINIUM FOIL"); s.add("BATTERIES"); s.add("BISCUITS"); s.add("BODY LOTION");
        s.add("BREAD"); s.add("BUTTER"); s.add("CASHEWS"); s.add("CEREAL BOX"); s.add("CHEESE");
        s.add("CHOCOLATE SYRUP"); s.add("CLEANER - FLOOR"); s.add("CLEANER - GLASS"); s.add("CLEANER - TOILET"); s.add("COFFEE");
        s.add("CONDITIONER"); s.add("COOKIES"); s.add("DAL - CHANNA"); s.add("DAL - MOONG"); s.add("DAL - URAD");
        s.add("DEODRANT"); s.add("DETERGENT"); s.add("EAR BUDS"); s.add("ENERGY DRINK"); s.add("FROZEN CORN");
        s.add("FROZEN GREEN PEAS"); s.add("GARBAGE BAGS"); s.add("GHEE"); s.add("HAIR OIL"); s.add("HAND SANITIZER");
        s.add("HAND WASH LIQUID"); s.add("HONEY"); s.add("JAGGERY"); s.add("JAM"); s.add("MAIDA");
        s.add("MAYONNAISE"); s.add("NOODLES"); s.add("OIL - OLIVE"); s.add("OIL - RICE BRAN"); s.add("OIL - SUNFLOWER");
        s.add("PAPAD"); s.add("PASTA"); s.add("PERFUME"); s.add("PICKLE - MANGO"); s.add("PICKLE - MIXED");
        s.add("POPCORN"); s.add("POWDER - GARAM MASALA"); s.add("POWDER - RED CHILLI"); s.add("RAISINS"); s.add("RAWA");
        s.add("RICE"); s.add("SALT"); s.add("SHAMPOO"); s.add("SOAP - BODY"); s.add("SOAP - DISHWASH");
        s.add("SOAP - LAUNDRY"); s.add("SUGAR"); s.add("TALCUM POWDER"); s.add("TEA"); s.add("TOILET PAPER ROLL"); 
        s.add("TOMATO KETCHUP"); s.add("TOOTHBRUSH"); s.add("TOOTHPASTE"); s.add("WHEAT FLOUR");
    }
    
    public void clear()
    {
        tfPID.setText("");
        tfName.setText("");
        tfUnit.setText("");
        tfPrice.setText("");
        tfQty.setText("");
        tfDiscount.setText("");
        tfAmount.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCompGST = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfInvoiceNo = new javax.swing.JTextField();
        tfGSTIN = new javax.swing.JTextField();
        tfDate = new javax.swing.JTextField();
        tfPID = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfUnit = new javax.swing.JTextField();
        tfPrice = new javax.swing.JTextField();
        tfQty = new javax.swing.JTextField();
        tfDiscount = new javax.swing.JTextField();
        tfAmount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProd = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfNo = new javax.swing.JTextField();
        tfTotal = new javax.swing.JTextField();
        tfCGST = new javax.swing.JTextField();
        tfSGST = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 255));
        setMinimumSize(new java.awt.Dimension(803, 691));
        setPreferredSize(new java.awt.Dimension(1366, 729));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(228, 241, 254));
        jLabel1.setFont(new java.awt.Font("Century", 2, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MYSTIC MART");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Invoice No.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Date & Time");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Customer ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Customer Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Customer Contact No.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Customer GSTIN");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Company GSTIN");

        lblCompGST.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Product ID");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Discount Per Unit");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Name");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Price Per Unit");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Quantity");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Amount");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Unit");

        tfInvoiceNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tfGSTIN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfGSTIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGSTINActionPerformed(evt);
            }
        });

        tfDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tfPID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfPID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPIDActionPerformed(evt);
            }
        });

        tfName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });
        tfName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNameKeyReleased(evt);
            }
        });

        tfUnit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfUnit.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfQty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfDiscount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfDiscount.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("SEARCH ITEM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("CALCULATE PRICE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("ADD ITEM");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tblProd.setAutoCreateRowSorter(true);
        tblProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT ID", "PRODUCT NAME", "PRODUCT UNIT", "PRODUCT PRICE/UNIT", "QUANTITY", "DISCOUNT %", "AMOUNT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProd.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblProd);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("CGST @ 6.00% ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("SGST @ 6.00%");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("# of Items");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Grand Total");

        tfNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoActionPerformed(evt);
            }
        });

        tfTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfCGST.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfCGST.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfSGST.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfSGST.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("CLEAR PRODUCT TABLE LIST");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("GENERATE INVOICE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("REMOVE ITEM");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCGST, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSGST, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jButton7)
                        .addGap(54, 54, 54)
                        .addComponent(jButton5)
                        .addGap(41, 41, 41)
                        .addComponent(jButton6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(tfInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfGSTIN, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(lblCompGST, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel9)
                        .addGap(174, 174, 174)
                        .addComponent(jLabel11)
                        .addGap(150, 150, 150)
                        .addComponent(jLabel16)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel12)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel13)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel10)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(tfPID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(tfUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(tfQty, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(tfDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jButton1)
                        .addGap(43, 43, 43)
                        .addComponent(jButton2)
                        .addGap(43, 43, 43)
                        .addComponent(jButton3)
                        .addGap(43, 43, 43)
                        .addComponent(jButton4)))
                .addGap(0, 117, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGSTIN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompGST, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfNo)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfCGST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(tfSGST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void tfGSTINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGSTINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGSTINActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void tfNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNameKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_BACKSPACE||evt.getKeyCode()==KeyEvent.VK_DELETE)
        {
            
        }
        else
        {
            String to_check = tfName.getText().toUpperCase();
            int to_check_len = to_check.length();
            for( String data : s)
            {
                String check_from_data="";
                for(int i=0; i<to_check_len;i++)
                    if(to_check_len <= data.length())
                        check_from_data=check_from_data+data.charAt(i);
                if(check_from_data.equals(to_check))
                {
                    tfName.setText(data);
                    tfName.setSelectionStart(to_check_len);
                    tfName.setSelectionEnd(data.length());
                    break;
                }
            }
        }
    }//GEN-LAST:event_tfNameKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            if(tfName.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(Billing.this, "Please Enter the Name of Product you want to Purchase.");
                return;
            }
            tfQty.setText("");
            tfAmount.setText("");
            Scanner sc = new Scanner(new File("PRODUCTS.csv"));
            sc.useDelimiter(",|\\n");
            while(sc.hasNext())
                if(sc.next().trim().equals(tfName.getText()))
                {
                    String PID = sc.next();
                    tfPID.setText(PID);
                    String Unit = sc.next();
                    tfUnit.setText(Unit);
                    String Price = sc.next();
                    tfPrice.setText(Price);
                    String Discount = sc.next();
                    tfDiscount.setText(Discount+"%");
                }
            sc.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPIDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(tfPrice.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(Billing.this, "Please Click on \"SEARCH ITEM\" before Calculating the Price of a Product.");
            return;
        }
        if(tfQty.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(Billing.this, "Please Enter the Quantity of the Product you Want to Purchase");
            return;
        }
        String Price = tfPrice.getText();
        String Quantity = tfQty.getText();
        String Discount = tfDiscount.getText();
        int Disc_len = Discount.length();
        Discount = Discount.substring(0, Disc_len-2);
        int price = Integer.parseInt(Price);
        int quantity = Integer.parseInt(Quantity);
        int discount = Integer.parseInt(Discount);
        price = price - ((price*discount)/100);
        int amount = price * quantity;
        String Amount = Integer.toString(amount);
        tfAmount.setText(Amount);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(tfPrice.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(Billing.this, "Please Click on \"SEARCH ITEM\" before Adding the Product to the Cart.");
            return;
        }
        if(tfAmount.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(Billing.this, "Please Click on \"CALCULATE PRICE\" before Adding the Product to the Cart.");
            return;
        }
        model.insertRow(tblProd.getRowCount(), new Object[]
        {
            tfPID.getText(),
            tfName.getText(),
            tfUnit.getText(),
            tfPrice.getText(),
            tfQty.getText(),
            tfDiscount.getText(),
            tfAmount.getText()
        });
        no_items = no_items+1;
        String no = Integer.toString(no_items);
        tfNo.setText(no);
        int TOTAL = Integer.parseInt(tfAmount.getText());
        total = total + TOTAL - cgst - sgst;
        cgst = ((total*6)/100);
        sgst = ((total*6)/100);
        String CGST = Integer.toString(cgst);
        tfCGST.setText(CGST);
        String SGST = Integer.toString(sgst);
        tfSGST.setText(SGST);
        total = total + cgst + sgst;
        String Total = Integer.toString(total);
        tfTotal.setText(Total);
        clear();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
       tblProd.clearSelection();
    }//GEN-LAST:event_formMouseClicked

    private void tfNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if( tblProd.getRowCount() == 0 )
        {
            JOptionPane.showMessageDialog(Billing.this, "The CART is Already EMPTY.");
            return;
        }
        
        if ( tblProd.getSelectedRow() == -1)
        {
            JOptionPane.showMessageDialog(Billing.this, "Please Select The Product From the Table To REMOVE it.");
            return;
        }
        int p = JOptionPane.showConfirmDialog(null,"Are You Sure you want to Delete The Product?", "Delete A Product", JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
            if(tblProd.getRowCount()==1)
            {
                no_items=0;
                cgst=0;
                sgst=0;
                total=0;
                tfNo.setText("");
                tfCGST.setText("");
                tfSGST.setText("");
                tfTotal.setText("");
            }
            else
            {
                no_items = no_items-1;
                String no = Integer.toString(no_items);
                tfNo.setText(no);
                int row = tblProd.getSelectedRow();
                String str = (tblProd.getModel().getValueAt(row,6).toString());
                int TOTAL = Integer.parseInt(str);
                total = total - TOTAL - cgst - sgst;
                cgst = ((total*6)/100);
                sgst = ((total*6)/100);
                String CGST = Integer.toString(cgst);
                tfCGST.setText(CGST);
                String SGST = Integer.toString(sgst);
                tfSGST.setText(SGST);
                total = total + cgst + sgst;
                String Total = Integer.toString(total);
                tfTotal.setText(Total);
            }
            model.removeRow(tblProd.getSelectedRow());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if( tblProd.getRowCount() == 0 )
        {
            JOptionPane.showMessageDialog(Billing.this, "The CART is Already EMPTY.");
            return;
        }
        int p = JOptionPane.showConfirmDialog(null,"Are You Sure you want to Clear The Product List?"
                + "\nNOTE: Once Deleted, Changes Can't be Reversed.", "Clear Product List", JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
            no_items=0;
            cgst=0;
            sgst=0;
            total=0;
            tfNo.setText("");
            tfCGST.setText("");
            tfSGST.setText("");
            tfTotal.setText("");
            model.setRowCount(0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if( tblProd.getRowCount() == 0 )
        {
            JOptionPane.showMessageDialog(Billing.this, "The CART is Already EMPTY. Cannot Generate An Invoice.");
            return;
        }
        int q = JOptionPane.showConfirmDialog(null,"Do You Want to Add or Remove a Product?", "Generate Bill", JOptionPane.YES_NO_OPTION);
        if(q!=0)
        {
            int p = JOptionPane.showConfirmDialog(null,"Are You Sure you want to Continue?"
                + "\nNOTE: Once Processed, Changes Can't be Reversed.", "Generate Bill", JOptionPane.YES_NO_OPTION);
            if(p==0)
            {
                try {
                    this.dispose();
                    Invoice i = new Invoice();
                    i.setVisible(true);
                    return;
                } catch (IOException ex) {
                    Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Billing().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextField3;
    public static javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblCompGST;
    public static javax.swing.JTable tblProd;
    private javax.swing.JTextField tfAmount;
    public static javax.swing.JTextField tfCGST;
    public static javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfDiscount;
    private javax.swing.JTextField tfGSTIN;
    public static javax.swing.JTextField tfInvoiceNo;
    private javax.swing.JTextField tfName;
    public static javax.swing.JTextField tfNo;
    private javax.swing.JTextField tfPID;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfQty;
    public static javax.swing.JTextField tfSGST;
    public static javax.swing.JTextField tfTotal;
    private javax.swing.JTextField tfUnit;
    // End of variables declaration//GEN-END:variables
}
